name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download nasm
      run: sudo apt-get install nasm
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
