name: Famine CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup env
      run: sudo apt-get install make nasm
    - name: make Famine
      run: make
    - name: make debug-Famine
      run: make BUILD=debug

  test:
    needs: build

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup env
      run: sudo apt-get install make nasm shunit2
    - name: make Famine
      run: make
    - name: check running process
      run: ps -aux
    - name: run tests
      run: ./test/script.sh
