name: Famine CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: download packages
      run: sudo apt-get install make nasm shunit2
    - name: make Famine
      run: make

  test:

    runs-on: ubuntu-latest

    steps:
    - name: run tests
      run: ./test/script.sh
